highlighter: rouge
markdown: kramdown
host: 0.0.0.0

subscribe_rss: /atom.xml
kramdown:
  input: GFM
  hard_wrap: false

base_path: https://spoqa.github.io/spoqa-han-sans/  # Change in your local dev environment
